Error if cannot find placeholder ip

diff --git a/update_hosts_preferred b/update_hosts_preferred
--- a/update_hosts_preferred
+++ b/update_hosts_preferred
@@ -6,15 +6,18 @@
 #
 # Author: Jonathan A. Epstein
 
-# Update the IP (key) in your hosts file containing the "PLACEHOLDER_HOST_NAME".
+# Update the IP (key) in your hosts file containing the "PLACEHOLDER_HOSTNAME".
 # @Params: $1 the IP to set
 set_hosts_variable_ip() {
-    local PLACEHOLDER_HOST_NAME='variable.ip'
+    local PLACEHOLDER_HOSTNAME='variable.ip'
     local placeholer_line
     # TODO: Do not update hosts files if no change
-    if placeholer_line=$(cat /etc/hosts | grep ${PLACEHOLDER_HOST_NAME}); then
+    if placeholer_line=$(cat /etc/hosts | grep ${PLACEHOLDER_HOSTNAME}); then
         new_placeholder_line=$(echo "${placeholer_line}" | { printf "${1} "; cut -d " " -f2-; } )
         sudo sed -i '.bak' "s~${placeholer_line}~${new_placeholder_line}~" /etc/hosts
+    else
+        echo "Could not find the placeholder hostname(\"${PLACEHOLDER_HOSTNAME}\")" >&2
+        exit 1
     fi
 }
 
